runtime: nodejs18 # or another supported version
env: standard
instance_class: F2
env_variables:
  MONGO_URI: "mongodb+srv://matthewlese:Dfb2UG0ZWHrAbjBp@cluster0.hi8ss.mongodb.net/myFirstDatabase?retryWrites=true&w=majority",
  SECRET_OR_KEY: "secret"